import mongoose from "mongoose";
import { TokenDataItem } from "../common/types";

const TokenSchema = new mongoose.Schema<TokenDataItem>({
  vol_24hr: String,
  narrative: [String],
  is_coin: Number,
  pc_1_hr: Number,
  pc_6_hr: Number,
  pc_24_hr: Number,
  liquidity: Number,
  market_cap: String,
  chain: String,
  token_name: String,
  trading_since: String,
  age_in_seconds: String,
  pair_created_at: String,
  token_icon: String,
  mentions_change_7_d: Number,
  mentions_change_24_hr: Number,
  mentions_change_1_hr: Number,
  followers_count: Number,
  twitter: String,
  telegram: String,
  mention_count_1hr: Number,
  mention_count_24hr: Number,
  mention_count_15min: Number,
  mention_count_6hr: Number,
  total_unique_accounts: Number,
  total_unique_accounts_24hr: Number,
  token_id: { type: String, unique: true, index: true },
  pair_id: String,
  token_symbol: String,
  buy_tax: Number,
  sell_tax: Number,
  is_contract_verified: Number,
  lp_lock_percentage: Number,
  lp_burned: Number,
  is_honeypot: Number,
  "24_hr_data": {
    change: String,
    total_volume: Number,
  },
  holders_count: Number,
  token_twitter: String,
  token_telegram: String,
  token_twitter_account: String,
  token_telegram_account: String,
  token_website: String,
  dex_url: String,
  influencer_count_24hr: String,
  is_cmc_listed: { type: mongoose.Schema.Types.Mixed },
  is_cg_listed: { type: mongoose.Schema.Types.Mixed },
  is_coinbase: { type: mongoose.Schema.Types.Mixed },
  is_gateio: { type: mongoose.Schema.Types.Mixed },
  is_bingx: { type: mongoose.Schema.Types.Mixed },
  is_mexc: { type: mongoose.Schema.Types.Mixed },
  is_okx: { type: mongoose.Schema.Types.Mixed },
  is_binance: { type: mongoose.Schema.Types.Mixed },
  is_bybit: { type: mongoose.Schema.Types.Mixed },
  is_kucoin: { type: mongoose.Schema.Types.Mixed },
  is_bitget: { type: mongoose.Schema.Types.Mixed },
  is_bitmart: { type: mongoose.Schema.Types.Mixed },
  smart_followers: Number,
  t_1hr_mentions: Number,
  t_2hr_mentions: Number,
  t_3hr_mentions: Number,
  t_4hr_mentions: Number,
  t_5hr_mentions: Number,
  t_6hr_mentions: Number,
  t_7hr_mentions: Number,
  t_8hr_mentions: Number,
  t_9hr_mentions: Number,
  hourly_median: Number,
  t_1d_mentions: Number,
  t_2d_mentions: Number,
  t_3d_mentions: Number,
  t_4d_mentions: Number,
  t_5d_mentions: Number,
  t_6d_mentions: Number,
  t_7d_mentions: Number,
  t_8d_mentions: Number,
  t_9d_mentions: Number,
  daily_median: Number,
  token_supply: Number,
  token_supply_dex: Number,
  profile_image_url: String,
  ath_market_cap: Number,
  ath_timestamp: String,
  market_data_source: String,
  cmc_slug: String,
  createdAt: { type: Number, default: Date.now },
  updatedAt: { type: Number, default: Date.now },
});

// Add indexes for commonly queried fields
TokenSchema.index({ chain: 1 });
TokenSchema.index({ market_cap: 1 });
TokenSchema.index({ liquidity: 1 });
TokenSchema.index({ mention_count_24hr: 1 });
TokenSchema.index({ createdAt: 1 });

const TokenModel = mongoose.model<TokenDataItem>("Token", TokenSchema);

export default TokenModel;
